## File for testing Alexa's honeycomb implementation

First test bond_params function.

In [1]:
from gen_1band_unified_hub_alexa import bond_params
import numpy as np

# Test for square lattice
geometry = "square"
Nx, Ny = 4, 4
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0

(bps, num_b, num_b_accum), map_b, degen_b, bonds = bond_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

# Print outputs
print(f"Bonds per site: {bps}")
print(f"Total bonds: {num_b}")
print(f"Accumulated bonds: {num_b_accum}")
print(f"\nmap_b shape: {map_b.shape}")
print(f"map_b (first 20): {map_b[:20]}")
print(f"\ndegen_b shape: {degen_b.shape}")
print(f"degen_b: {degen_b}")
print(f"\nbonds shape: {bonds.shape}")
print(f"First few bonds:\n{bonds[:, :8]}")

Bonds per site: 2
Total bonds: 32
Accumulated bonds: 2

map_b shape: (32,)
map_b (first 20): [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]

degen_b shape: (2,)
degen_b: [16 16]

bonds shape: (2, 32)
First few bonds:
[[0 1 2 3 4 5 6 7]
 [1 2 3 0 5 6 7 4]]


In [3]:
from gen_1band_unified_hub_alexa import bond_params
import numpy as np

# Test for square lattice
geometry = "honeycomb"
Nx, Ny = 3, 3
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0

(bps, num_b, num_b_accum), map_b, degen_b, bonds = bond_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

# Print outputs
print(f"Bonds per site: {bps}")
print(f"Total bonds: {num_b}")
print(f"Accumulated bonds: {num_b_accum}")
print(f"\nmap_b shape: {map_b.shape}")
print(f"map_b (first 20): {map_b[:20]}")
print(f"\ndegen_b shape: {degen_b.shape}")
print(f"degen_b: {degen_b}")
print(f"\nbonds shape: {bonds.shape}")
print(f"First few bonds (horizontal):\n{bonds[:, :8]}")
print(f"First few bonds along x:\n{bonds[:,Nx*Ny:Nx*Ny+8]}")
print(f"First few bonds along y:\n{bonds[:,2*Nx*Ny:2*Nx*Ny+8]}")
print(f"All bonds:\n{bonds}")

Bonds per site: 1.5
Total bonds: 27
Accumulated bonds: 3

map_b shape: (27,)
map_b (first 20): [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 2 2]

degen_b shape: (3,)
degen_b: [9 9 9]

bonds shape: (2, 27)
First few bonds (horizontal):
[[ 0  1  2  3  4  5  6  7]
 [ 9 10 11 12 13 14 15 16]]
First few bonds along x:
[[ 0  1  2  3  4  5  6  7]
 [11  9 10 14 12 13 17 15]]
First few bonds along y:
[[ 0  1  2  3  4  5  6  7]
 [15 16 17  9 10 11 12 13]]
All bonds:
[[ 0  1  2  3  4  5  6  7  8  0  1  2  3  4  5  6  7  8  0  1  2  3  4  5
   6  7  8]
 [ 9 10 11 12 13 14 15 16 17 11  9 10 14 12 13 17 15 16 15 16 17  9 10 11
  12 13 14]]


Next test bond2_params function.

In [5]:
from gen_1band_unified_hub_alexa import bond2_params
import numpy as np

# Test for square lattice
geometry = "square"
Nx, Ny = 4, 4
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0

(b2ps, num_b2, num_b2_accum), map_b2, degen_b2, bond2s = bond2_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

# Print outputs
print(f"Bond2s per site: {b2ps}")
print(f"Total bond2s: {num_b2}")
print(f"Accumulated bond2s: {num_b2_accum}")
print(f"\nmap_b2 shape: {map_b2.shape}")
print(f"map_b2 (first 20): {map_b2[:20]}")
print(f"\ndegen_b2 shape: {degen_b2.shape}")
print(f"degen_b2: {degen_b2}")
print(f"\nbond2s shape: {bond2s.shape}")
print(f"First few bond2s:\n{bond2s[:, :8]}")

Bond2s per site: 4
Total bond2s: 64
Accumulated bond2s: 4

map_b2 shape: (64,)
map_b2 (first 20): [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]

degen_b2 shape: (4,)
degen_b2: [16 16 16 16]

bond2s shape: (2, 64)
First few bond2s:
[[0 1 2 3 4 5 6 7]
 [2 3 0 1 6 7 4 5]]


In [6]:
from gen_1band_unified_hub_alexa import bond2_params
import numpy as np

# Test for square lattice
geometry = "honeycomb"
Nx, Ny = 3, 3
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0
N = Nx * Ny * 2 # norb per cell = 2

(b2ps, num_b2, num_b2_accum), map_b2, degen_b2, bond2s = bond2_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

# Print outputs
print(f"Bond2s per site: {b2ps}")
print(f"Total bond2s: {num_b2}")
print(f"Accumulated bond2s: {num_b2_accum}")
print(f"\nmap_b2 shape: {map_b2.shape}")
print(f"map_b2 (first 20): {map_b2[:20]}")
print(f"\ndegen_b2 shape: {degen_b2.shape}")
print(f"degen_b2: {degen_b2}")
print(f"\nbond2s shape: {bond2s.shape}")
print(f"First few bond2s:\n{bond2s[:, :8]}")
print(f"Whole bonds array:\n{bond2s}")

Bond2s per site: 3
Total bond2s: 54
Accumulated bond2s: 3

map_b2 shape: (54,)
map_b2 (first 20): [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]

degen_b2 shape: (3,)
degen_b2: [18 18 18]

bond2s shape: (2, 54)
First few bond2s:
[[0 1 2 3 4 5 6 7]
 [1 2 0 4 5 3 7 8]]
Whole bonds array:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5
   6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5  6  7  8  9 10 11
  12 13 14 15 16 17]
 [ 1  2  0  4  5  3  7  8  6 10 11  9 13 14 12 16 17 15  3  4  5  6  7  8
   0  1  2 12 13 14 15 16 17  9 10 11  7  8  6  1  2  0  4  5  3 16 17 15
  10 11  9 13 14 12]]


In [9]:
print(map_b2[2*18:3*18])

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


Next test implementations in the `create_1()` function. Start with map_ij.

In [ ]:
# square implementation, copied from gen_1band_unified_hub.py

# Test for square lattice
geometry = "square"
Nx, Ny = 4, 4
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0
N = Nx * Ny # norb per cell = 2

# 2 site mapping: site r = (x,y) has total (column order) index x + Nx * y
map_ij = np.zeros((N, N), dtype=np.int32)
num_ij = N if trans_sym else N * N
degen_ij = np.zeros(num_ij, dtype=np.int32)
for jy in range(Ny):
    for jx in range(Nx):
        for iy in range(Ny):
            for ix in range(Nx):
                if trans_sym:
                    ky = (iy - jy) % Ny
                    kx = (ix - jx) % Nx
                    k = kx + Nx * ky
                else:
                    k = (ix + Nx * iy) + N * (jx + Nx * jy)
                map_ij[jx + Nx * jy, ix + Nx * iy] = k
                degen_ij[k] += 1
assert num_ij == map_ij.max() + 1 == degen_ij.size
assert np.all(degen_ij == degen_ij[0])

print(map_ij)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 3  0  1  2  7  4  5  6 11  8  9 10 15 12 13 14]
 [ 2  3  0  1  6  7  4  5 10 11  8  9 14 15 12 13]
 [ 1  2  3  0  5  6  7  4  9 10 11  8 13 14 15 12]
 [12 13 14 15  0  1  2  3  4  5  6  7  8  9 10 11]
 [15 12 13 14  3  0  1  2  7  4  5  6 11  8  9 10]
 [14 15 12 13  2  3  0  1  6  7  4  5 10 11  8  9]
 [13 14 15 12  1  2  3  0  5  6  7  4  9 10 11  8]
 [ 8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7]
 [11  8  9 10 15 12 13 14  3  0  1  2  7  4  5  6]
 [10 11  8  9 14 15 12 13  2  3  0  1  6  7  4  5]
 [ 9 10 11  8 13 14 15 12  1  2  3  0  5  6  7  4]
 [ 4  5  6  7  8  9 10 11 12 13 14 15  0  1  2  3]
 [ 7  4  5  6 11  8  9 10 15 12 13 14  3  0  1  2]
 [ 6  7  4  5 10 11  8  9 14 15 12 13  2  3  0  1]
 [ 5  6  7  4  9 10 11  8 13 14 15 12  1  2  3  0]]


In [14]:
print(map_ij[1,10])
print(map_ij[15,0])

9
5


In [15]:

geometry = "honeycomb"
Nx, Ny = 3, 3
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0
Norb = 2
N = Nx * Ny * Norb # norb per cell = 2


# honeycomb implementation, copied

# 2 site mapping
map_ij = np.zeros((N, N), dtype=np.int32)
num_ij = Norb * Norb * Ny * Nx if trans_sym else N * N
degen_ij = np.zeros(num_ij, dtype=np.int32)
for jo in range(Norb):
    for jy in range(Ny):
        for jx in range(Nx):
            for io in range(Norb):
                for iy in range(Ny):
                    for ix in range(Nx):
                        if trans_sym:
                            ky = (iy - jy) % Ny
                            kx = (ix - jx) % Nx
                            # total column index of matrix index [kx,ky,io,jo]
                            k = kx + Nx * ky + Nx * Ny * io + N * jo
                        else:
                            # total column index of matrix index [ix,iy,io,jx,jy,jo]
                            k = (ix + Nx * iy + Nx * Ny * io) + N * (
                                jx + Nx * jy + Nx * Ny * jo
                            )
                        map_ij[
                            jx + Nx * jy + Nx * Ny * jo,
                            ix + Nx * iy + Nx * Ny * io,
                        ] = k
                        degen_ij[k] += 1
assert num_ij == map_ij.max() + 1 == degen_ij.size
assert np.all(degen_ij == degen_ij[0])

print(map_ij)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [ 2  0  1  5  3  4  8  6  7 11  9 10 14 12 13 17 15 16]
 [ 1  2  0  4  5  3  7  8  6 10 11  9 13 14 12 16 17 15]
 [ 6  7  8  0  1  2  3  4  5 15 16 17  9 10 11 12 13 14]
 [ 8  6  7  2  0  1  5  3  4 17 15 16 11  9 10 14 12 13]
 [ 7  8  6  1  2  0  4  5  3 16 17 15 10 11  9 13 14 12]
 [ 3  4  5  6  7  8  0  1  2 12 13 14 15 16 17  9 10 11]
 [ 5  3  4  8  6  7  2  0  1 14 12 13 17 15 16 11  9 10]
 [ 4  5  3  7  8  6  1  2  0 13 14 12 16 17 15 10 11  9]
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
 [20 18 19 23 21 22 26 24 25 29 27 28 32 30 31 35 33 34]
 [19 20 18 22 23 21 25 26 24 28 29 27 31 32 30 34 35 33]
 [24 25 26 18 19 20 21 22 23 33 34 35 27 28 29 30 31 32]
 [26 24 25 20 18 19 23 21 22 35 33 34 29 27 28 32 30 31]
 [25 26 24 19 20 18 22 23 21 34 35 33 28 29 27 31 32 30]
 [21 22 23 24 25 26 18 19 20 30 31 32 33 34 35 27 28 29]
 [23 21 22 26 24 25 20 18 19 32 30 31 35 33 34 29 27 28]
 [22 23 21 25 26 24 19 20 18 31