## File for testing Alexa's honeycomb implementation

First test bond_params function.

In [1]:
from gen_1band_unified_hub_alexa import bond_params
import numpy as np

# Test for square lattice
geometry = "square"
Nx, Ny = 4, 4
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0

(bps, num_b, num_b_accum), map_b, degen_b, bonds = bond_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

# Print outputs
print(f"Bonds per site: {bps}")
print(f"Total bonds: {num_b}")
print(f"Accumulated bonds: {num_b_accum}")
print(f"\nmap_b shape: {map_b.shape}")
print(f"map_b (first 20): {map_b[:20]}")
print(f"\ndegen_b shape: {degen_b.shape}")
print(f"degen_b: {degen_b}")
print(f"\nbonds shape: {bonds.shape}")
print(f"First few bonds:\n{bonds[:, :8]}")

Bonds per site: 2
Total bonds: 32
Accumulated bonds: 2

map_b shape: (32,)
map_b (first 20): [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]

degen_b shape: (2,)
degen_b: [16 16]

bonds shape: (2, 32)
First few bonds:
[[0 1 2 3 4 5 6 7]
 [1 2 3 0 5 6 7 4]]


In [3]:
from gen_1band_unified_hub_alexa import bond_params
import numpy as np

# Test for square lattice
geometry = "honeycomb"
Nx, Ny = 3, 3
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0

(bps, num_b, num_b_accum), map_b, degen_b, bonds = bond_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

# Print outputs
print(f"Bonds per site: {bps}")
print(f"Total bonds: {num_b}")
print(f"Accumulated bonds: {num_b_accum}")
print(f"\nmap_b shape: {map_b.shape}")
print(f"map_b (first 20): {map_b[:20]}")
print(f"\ndegen_b shape: {degen_b.shape}")
print(f"degen_b: {degen_b}")
print(f"\nbonds shape: {bonds.shape}")
print(f"First few bonds (horizontal):\n{bonds[:, :8]}")
print(f"First few bonds along x:\n{bonds[:,Nx*Ny:Nx*Ny+8]}")
print(f"First few bonds along y:\n{bonds[:,2*Nx*Ny:2*Nx*Ny+8]}")
print(f"All bonds:\n{bonds}")

Bonds per site: 1.5
Total bonds: 27
Accumulated bonds: 3

map_b shape: (27,)
map_b (first 20): [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 2 2]

degen_b shape: (3,)
degen_b: [9 9 9]

bonds shape: (2, 27)
First few bonds (horizontal):
[[ 0  1  2  3  4  5  6  7]
 [ 9 10 11 12 13 14 15 16]]
First few bonds along x:
[[ 0  1  2  3  4  5  6  7]
 [11  9 10 14 12 13 17 15]]
First few bonds along y:
[[ 0  1  2  3  4  5  6  7]
 [15 16 17  9 10 11 12 13]]
All bonds:
[[ 0  1  2  3  4  5  6  7  8  0  1  2  3  4  5  6  7  8  0  1  2  3  4  5
   6  7  8]
 [ 9 10 11 12 13 14 15 16 17 11  9 10 14 12 13 17 15 16 15 16 17  9 10 11
  12 13 14]]


Next test bond2_params function.

In [1]:
from gen_1band_unified_hub_alexa import bond2_params
import numpy as np

# Test for square lattice
geometry = "square"
Nx, Ny = 4, 4
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0

(b2ps, num_b2, num_b2_accum), map_b2, degen_b2, bond2s = bond2_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

# Print outputs
print(f"Bond2s per site: {b2ps}")
print(f"Total bond2s: {num_b2}")
print(f"Accumulated bond2s: {num_b2_accum}")
print(f"\nmap_b2 shape: {map_b2.shape}")
print(f"map_b2 (first 20): {map_b2[:20]}")
print(f"\ndegen_b2 shape: {degen_b2.shape}")
print(f"degen_b2: {degen_b2}")
print(f"\nbond2s shape: {bond2s.shape}")
print(f"First few bond2s:\n{bond2s[:, :8]}")

Bond2s per site: 4
Total bond2s: 64
Accumulated bond2s: 4

map_b2 shape: (64,)
map_b2 (first 20): [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]

degen_b2 shape: (4,)
degen_b2: [16 16 16 16]

bond2s shape: (2, 64)
First few bond2s:
[[0 1 2 3 4 5 6 7]
 [2 3 0 1 6 7 4 5]]


In [3]:
from gen_1band_unified_hub_alexa import bond2_params
import numpy as np

# Test for square lattice
geometry = "honeycomb"
Nx, Ny = 3, 3
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0
N = Nx * Ny * 2 # norb per cell = 2

(b2ps, num_b2, num_b2_accum), map_b2, degen_b2, bond2s = bond2_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

# Print outputs
print(f"Bond2s per site: {b2ps}")
print(f"Total bond2s: {num_b2}")
print(f"Accumulated bond2s: {num_b2_accum}")
print(f"\nmap_b2 shape: {map_b2.shape}")
print(f"map_b2 (first 20): {map_b2[:20]}")
print(f"\ndegen_b2 shape: {degen_b2.shape}")
print(f"degen_b2: {degen_b2}")
print(f"\nbond2s shape: {bond2s.shape}")
print(f"First few bond2s:\n{bond2s[:, :8]}")
print(f"Whole bonds array:\n{bond2s}")

Bond2s per site: 3
Total bond2s: 54
Accumulated bond2s: 6

map_b2 shape: (54,)
map_b2 (first 20): [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 2 2]

degen_b2 shape: (6,)
degen_b2: [9 9 9 9 9 9]

bond2s shape: (2, 54)
First few bond2s:
[[0 1 2 3 4 5 6 7]
 [1 2 0 4 5 3 7 8]]
Whole bonds array:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5
   6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5  6  7  8  9 10 11
  12 13 14 15 16 17]
 [ 1  2  0  4  5  3  7  8  6 10 11  9 13 14 12 16 17 15  3  4  5  6  7  8
   0  1  2 12 13 14 15 16 17  9 10 11  7  8  6  1  2  0  4  5  3 16 17 15
  10 11  9 13 14 12]]


In [9]:
print(map_b2[2*18:3*18])

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


Next test implementations in the `create_1()` function. Start with map_ij.

In [ ]:
# square implementation, copied from gen_1band_unified_hub.py

# Test for square lattice
geometry = "square"
Nx, Ny = 4, 4
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0
N = Nx * Ny # norb per cell = 2

# 2 site mapping: site r = (x,y) has total (column order) index x + Nx * y
map_ij = np.zeros((N, N), dtype=np.int32)
num_ij = N if trans_sym else N * N
degen_ij = np.zeros(num_ij, dtype=np.int32)
for jy in range(Ny):
    for jx in range(Nx):
        for iy in range(Ny):
            for ix in range(Nx):
                if trans_sym:
                    ky = (iy - jy) % Ny
                    kx = (ix - jx) % Nx
                    k = kx + Nx * ky
                else:
                    k = (ix + Nx * iy) + N * (jx + Nx * jy)
                map_ij[jx + Nx * jy, ix + Nx * iy] = k
                degen_ij[k] += 1
assert num_ij == map_ij.max() + 1 == degen_ij.size
assert np.all(degen_ij == degen_ij[0])

print(map_ij)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 3  0  1  2  7  4  5  6 11  8  9 10 15 12 13 14]
 [ 2  3  0  1  6  7  4  5 10 11  8  9 14 15 12 13]
 [ 1  2  3  0  5  6  7  4  9 10 11  8 13 14 15 12]
 [12 13 14 15  0  1  2  3  4  5  6  7  8  9 10 11]
 [15 12 13 14  3  0  1  2  7  4  5  6 11  8  9 10]
 [14 15 12 13  2  3  0  1  6  7  4  5 10 11  8  9]
 [13 14 15 12  1  2  3  0  5  6  7  4  9 10 11  8]
 [ 8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7]
 [11  8  9 10 15 12 13 14  3  0  1  2  7  4  5  6]
 [10 11  8  9 14 15 12 13  2  3  0  1  6  7  4  5]
 [ 9 10 11  8 13 14 15 12  1  2  3  0  5  6  7  4]
 [ 4  5  6  7  8  9 10 11 12 13 14 15  0  1  2  3]
 [ 7  4  5  6 11  8  9 10 15 12 13 14  3  0  1  2]
 [ 6  7  4  5 10 11  8  9 14 15 12 13  2  3  0  1]
 [ 5  6  7  4  9 10 11  8 13 14 15 12  1  2  3  0]]


In [14]:
print(map_ij[1,10])
print(map_ij[15,0])

9
5


In [15]:

geometry = "honeycomb"
Nx, Ny = 3, 3
tp = 0.0  # or -0.3 for next-nearest neighbor
tpp = 0.0
trans_sym = 1  # or 0
Norb = 2
N = Nx * Ny * Norb # norb per cell = 2


# honeycomb implementation, copied

# 2 site mapping
map_ij = np.zeros((N, N), dtype=np.int32)
num_ij = Norb * Norb * Ny * Nx if trans_sym else N * N
degen_ij = np.zeros(num_ij, dtype=np.int32)
for jo in range(Norb):
    for jy in range(Ny):
        for jx in range(Nx):
            for io in range(Norb):
                for iy in range(Ny):
                    for ix in range(Nx):
                        if trans_sym:
                            ky = (iy - jy) % Ny
                            kx = (ix - jx) % Nx
                            # total column index of matrix index [kx,ky,io,jo]
                            k = kx + Nx * ky + Nx * Ny * io + N * jo
                        else:
                            # total column index of matrix index [ix,iy,io,jx,jy,jo]
                            k = (ix + Nx * iy + Nx * Ny * io) + N * (
                                jx + Nx * jy + Nx * Ny * jo
                            )
                        map_ij[
                            jx + Nx * jy + Nx * Ny * jo,
                            ix + Nx * iy + Nx * Ny * io,
                        ] = k
                        degen_ij[k] += 1
assert num_ij == map_ij.max() + 1 == degen_ij.size
assert np.all(degen_ij == degen_ij[0])

print(map_ij)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [ 2  0  1  5  3  4  8  6  7 11  9 10 14 12 13 17 15 16]
 [ 1  2  0  4  5  3  7  8  6 10 11  9 13 14 12 16 17 15]
 [ 6  7  8  0  1  2  3  4  5 15 16 17  9 10 11 12 13 14]
 [ 8  6  7  2  0  1  5  3  4 17 15 16 11  9 10 14 12 13]
 [ 7  8  6  1  2  0  4  5  3 16 17 15 10 11  9 13 14 12]
 [ 3  4  5  6  7  8  0  1  2 12 13 14 15 16 17  9 10 11]
 [ 5  3  4  8  6  7  2  0  1 14 12 13 17 15 16 11  9 10]
 [ 4  5  3  7  8  6  1  2  0 13 14 12 16 17 15 10 11  9]
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
 [20 18 19 23 21 22 26 24 25 29 27 28 32 30 31 35 33 34]
 [19 20 18 22 23 21 25 26 24 28 29 27 31 32 30 34 35 33]
 [24 25 26 18 19 20 21 22 23 33 34 35 27 28 29 30 31 32]
 [26 24 25 20 18 19 23 21 22 35 33 34 29 27 28 32 30 31]
 [25 26 24 19 20 18 22 23 21 34 35 33 28 29 27 31 32 30]
 [21 22 23 24 25 26 18 19 20 30 31 32 33 34 35 27 28 29]
 [23 21 22 26 24 25 20 18 19 32 30 31 35 33 34 29 27 28]
 [22 23 21 25 26 24 19 20 18 31

Now let's work on map_bs.

In [ ]:
from gen_1band_unified_hub_alexa import bond_params

geometry = "square"
Nx, Ny = 4, 4
tp = 0.0
tpp = 0.0
trans_sym = 0  # or 0
Norb = 1
N = Nx * Ny * Norb # norb per cell = 1 for square

(bps, num_b, num_b_accum), map_b, degen_b, bonds = bond_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

if geometry == "square":
    # 2 site mapping: site r = (x,y) has total (column order) index x + Nx * y
    map_ij = np.zeros((N, N), dtype=np.int32)
    num_ij = N if trans_sym else N * N
    degen_ij = np.zeros(num_ij, dtype=np.int32)
    for jy in range(Ny):
        for jx in range(Nx):
            for iy in range(Ny):
                for ix in range(Nx):
                    if trans_sym:
                        ky = (iy - jy) % Ny
                        kx = (ix - jx) % Nx
                        k = kx + Nx * ky
                    else:
                        k = (ix + Nx * iy) + N * (jx + Nx * jy)
                    map_ij[jx + Nx * jy, ix + Nx * iy] = k
                    degen_ij[k] += 1
    assert num_ij == map_ij.max() + 1 == degen_ij.size
    assert np.all(degen_ij == degen_ij[0])

    # 1 bond 1 site mapping
    # Translated to fortran order: [j,istuff] -> [istuff + num_b * j] -> [istuff,j]
    map_bs = np.zeros((N, num_b), dtype=np.int32)
    num_bs = bps * N if trans_sym else num_b * N
    degen_bs = np.zeros(num_bs, dtype=np.int32)
    for j in range(N):
        for i in range(N):
            k = map_ij[j, i]
            for ib in range(bps):
                kk = k + num_ij * ib
                map_bs[j, i + N * ib] = kk
                degen_bs[kk] += 1
    assert num_bs == map_bs.max() + 1 == degen_bs.size
    assert np.all(degen_bs == degen_bs[0])

    # 1 bond - 1 bond mapping
    # Translated to Fortran order: [jstuff ,istuff] -> [istuff + num_b * jstuff] -> [istuff,jstuff]
    map_bb = np.zeros((num_b, num_b), dtype=np.int32)
    num_bb = bps * bps * N if trans_sym else num_b * num_b
    degen_bb = np.zeros(num_bb, dtype=np.int32)
    for j in range(N):
        for i in range(N):
            k = map_ij[j, i]
            for jb in range(bps):
                for ib in range(bps):
                    kk = k + num_ij * (ib + bps * jb)
                    map_bb[j + N * jb, i + N * ib] = kk
                    degen_bb[kk] += 1
    assert num_bb == map_bb.max() + 1 == degen_bb.size
    assert np.all(degen_bb == degen_bb[0])


In [89]:
np.set_printoptions(linewidth=200)

# print(num_b)
# print(bps)
print(num_bs)
print(map_bs.shape)
print(map_bs)

512
(16, 32)
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287]
 [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 368 

In [133]:
from gen_1band_unified_hub_alexa import bond_params

geometry = "honeycomb"
Nx, Ny = 3, 3
tp = 0.0
tpp = 0.0
trans_sym = 0  # or 0
Norb = 2
N = Nx * Ny * Norb # norb per cell = 1 for square

(bps, num_b, num_b_accum), map_b, degen_b, bonds = bond_params(
    geometry, Nx, Ny, tp, tpp, trans_sym
)

if geometry == "honeycomb":
   # 2 site mapping
    map_ij = np.zeros((N, N), dtype=np.int32)
    num_ij = Norb * Norb * Ny * Nx if trans_sym else N * N
    degen_ij = np.zeros(num_ij, dtype=np.int32)
    for jo in range(Norb):
        for jy in range(Ny):
            for jx in range(Nx):
                for io in range(Norb):
                    for iy in range(Ny):
                        for ix in range(Nx):
                            if trans_sym:
                                ky = (iy - jy) % Ny
                                kx = (ix - jx) % Nx
                                # # total column index of matrix index [kx,ky,io,jo]
                                # k = kx + Nx * ky + Nx * Ny * io + N * jo

                                # NOTE: Alexa changed column ordering
                                # total column index of matrix index [kx,ky,jo,io]
                                k = kx + Nx * ky + Nx * Ny * jo + N * io
                            else:
                                # # total column index of matrix index [ix,iy,io,jx,jy,jo]
                                # k = (ix + Nx * iy + Nx * Ny * io) + N * (
                                #     jx + Nx * jy + Nx * Ny * jo
                                # )

                                # NOTE: Alexa changed column ordering
                                # total column index of matrix index [jx,jy,,ix,iy,jo,io]
                                k = jx + Nx * jy + Nx*Ny * ix + Nx*Ny*Nx * iy + Nx*Ny*Nx*Ny * jo + Nx*Ny*N * io
                                
                            map_ij[
                                jx + Nx * jy + Nx * Ny * jo,
                                ix + Nx * iy + Nx * Ny * io,
                            ] = k
                            degen_ij[k] += 1
    assert num_ij == map_ij.max() + 1 == degen_ij.size
    assert np.all(degen_ij == degen_ij[0])

    # print("Trans sym = ",trans_sym)
    # print("map",map_ij,map_ij.shape,"degen",degen_ij,degen_ij.shape,"num",num_ij)

    # 1 bond 1 site mapping NOTE: Alexa implemented but need to check
    map_bs = np.zeros((N, num_b), dtype=np.int32) # good
    num_bs = int(bps * N * Norb) if trans_sym else num_b * N # for trans_sym starting from A and B site not equivalent -> have to mult by Norb
    degen_bs = np.zeros(num_bs, dtype=np.int32) # I think good?
    bonds_per_cell = int(bps * Norb)
    for j in range(N):
        for i in range(Nx*Ny): # loops over all A sites in the lattice
            # similar to in bond_params() func we have to count bonds per cell not per site bc bps=1.5 and bpc=3
            # specifically for honeycomb, counting all 3 bonds from A sites counts all bonds in the lattice
            k = map_ij[j, i]
            num_k = N if trans_sym else N * Nx * Ny
            # trans_sym on: since we're only using the A sites for the i atom, the k index only runs through the first N with col indexing [kx,ky,jo,io] (missing last io index, io=0)
            # trans_sym off: still only using A sites for i atom -> k index runs through first N*Nx*Ny with col indexing [jx,jy,jo,ix,iy,io] (missing last io index bc io=0)
            for ib in range(bonds_per_cell):
                kk = k + num_k * ib # use num_k instead of num_ij here
                map_bs[j, i + Nx*Ny * ib] = kk
                degen_bs[kk] += 1
    assert num_bs == map_bs.max() + 1 == degen_bs.size
    assert np.all(degen_bs == degen_bs[0])

    # 1 bond - 1 bond mapping NOTE: Alexa implemented but need to check
    map_bb = np.zeros((num_b, num_b), dtype=np.int32)
    num_bb = int(bps * bps * N * Norb) if trans_sym else num_b * num_b # for honeycomb starting from A and B site not equivalent -> mult by Norb
    degen_bb = np.zeros(num_bb, dtype=np.int32)
    bonds_per_cell = int(bps * Norb)
    # Count bonds per unit cell like we did in bond_params, looping over A sites
    for j in range(Nx*Ny):
        for i in range(Nx*Ny):
            k = map_ij[j, i]
            num_k = Nx * Ny if trans_sym else Nx * Ny * Nx * Ny # trans_sym off not yet implemented
            for jb in range(bonds_per_cell):
                for ib in range(bonds_per_cell):
                    kk = k + num_k * (jb + bonds_per_cell * ib) # do I want to switch ib and jb here? Order seems kind of arbitrary. Does it matter?
                    map_bb[j + Nx*Ny * jb, i + Nx*Ny * ib] = kk
                    degen_bb[kk] += 1
    assert num_bb == map_bb.max() + 1 == degen_bb.size
    assert np.all(degen_bb == degen_bb[0])

In [134]:
print(num_bb)
# print(bonds_per_cell)
# print(map_ij.shape)
# print(map_ij[:,:Nx*Ny])
# print(map_ij[:,:Nx*Ny].shape)
# print(N + Nx*Ny)

# print(map_ij.max())

print(map_bb.shape)
# print(np.any(map_bs == 9))
print(map_bb)
print(np.max(map_bb))
print(degen_bb.shape)

729
(27, 27)
[[  0   9  18  27  36  45  54  63  72 243 252 261 270 279 288 297 306 315 486 495 504 513 522 531 540 549 558]
 [  1  10  19  28  37  46  55  64  73 244 253 262 271 280 289 298 307 316 487 496 505 514 523 532 541 550 559]
 [  2  11  20  29  38  47  56  65  74 245 254 263 272 281 290 299 308 317 488 497 506 515 524 533 542 551 560]
 [  3  12  21  30  39  48  57  66  75 246 255 264 273 282 291 300 309 318 489 498 507 516 525 534 543 552 561]
 [  4  13  22  31  40  49  58  67  76 247 256 265 274 283 292 301 310 319 490 499 508 517 526 535 544 553 562]
 [  5  14  23  32  41  50  59  68  77 248 257 266 275 284 293 302 311 320 491 500 509 518 527 536 545 554 563]
 [  6  15  24  33  42  51  60  69  78 249 258 267 276 285 294 303 312 321 492 501 510 519 528 537 546 555 564]
 [  7  16  25  34  43  52  61  70  79 250 259 268 277 286 295 304 313 322 493 502 511 520 529 538 547 556 565]
 [  8  17  26  35  44  53  62  71  80 251 260 269 278 287 296 305 314 323 494 503 512 521 530 539 5

In [128]:
# for j in range(Nx*Ny):
#     for i in range(Nx*Ny):
#         k = map_ij[j, i]
#         print(k)

print(map_ij[:Nx*Ny, :Nx*Ny])

[[ 0  9 18 27 36 45 54 63 72]
 [ 1 10 19 28 37 46 55 64 73]
 [ 2 11 20 29 38 47 56 65 74]
 [ 3 12 21 30 39 48 57 66 75]
 [ 4 13 22 31 40 49 58 67 76]
 [ 5 14 23 32 41 50 59 68 77]
 [ 6 15 24 33 42 51 60 69 78]
 [ 7 16 25 34 43 52 61 70 79]
 [ 8 17 26 35 44 53 62 71 80]]


In [127]:
print(num_bs)
# print(bonds_per_cell)
# print(map_ij.shape)
# print(map_ij[:,:Nx*Ny])
# print(map_ij[:,:Nx*Ny].shape)
# print(N + Nx*Ny)

# print(map_ij.max())

print(map_bs.shape)
# print(np.any(map_bs == 9))
print(map_bs)
print(np.max(map_bs))
print(degen_bs.shape)
print(degen_bs[:10])

486
(18, 27)
[[  0   9  18  27  36  45  54  63  72 162 171 180 189 198 207 216 225 234 324 333 342 351 360 369 378 387 396]
 [  1  10  19  28  37  46  55  64  73 163 172 181 190 199 208 217 226 235 325 334 343 352 361 370 379 388 397]
 [  2  11  20  29  38  47  56  65  74 164 173 182 191 200 209 218 227 236 326 335 344 353 362 371 380 389 398]
 [  3  12  21  30  39  48  57  66  75 165 174 183 192 201 210 219 228 237 327 336 345 354 363 372 381 390 399]
 [  4  13  22  31  40  49  58  67  76 166 175 184 193 202 211 220 229 238 328 337 346 355 364 373 382 391 400]
 [  5  14  23  32  41  50  59  68  77 167 176 185 194 203 212 221 230 239 329 338 347 356 365 374 383 392 401]
 [  6  15  24  33  42  51  60  69  78 168 177 186 195 204 213 222 231 240 330 339 348 357 366 375 384 393 402]
 [  7  16  25  34  43  52  61  70  79 169 178 187 196 205 214 223 232 241 331 340 349 358 367 376 385 394 403]
 [  8  17  26  35  44  53  62  71  80 170 179 188 197 206 215 224 233 242 332 341 350 359 368 377 3

In [110]:
# print(map_ij[:, :Nx*Ny])
print(np.sort(map_bs))

[[  0  18  36  54  72  90 108 126 144 162 180 198 216 234 252 270 288 306 324 342 360 378 396 414 432 450 468]
 [  1  19  37  55  73  91 109 127 145 163 181 199 217 235 253 271 289 307 325 343 361 379 397 415 433 451 469]
 [  2  20  38  56  74  92 110 128 146 164 182 200 218 236 254 272 290 308 326 344 362 380 398 416 434 452 470]
 [  3  21  39  57  75  93 111 129 147 165 183 201 219 237 255 273 291 309 327 345 363 381 399 417 435 453 471]
 [  4  22  40  58  76  94 112 130 148 166 184 202 220 238 256 274 292 310 328 346 364 382 400 418 436 454 472]
 [  5  23  41  59  77  95 113 131 149 167 185 203 221 239 257 275 293 311 329 347 365 383 401 419 437 455 473]
 [  6  24  42  60  78  96 114 132 150 168 186 204 222 240 258 276 294 312 330 348 366 384 402 420 438 456 474]
 [  7  25  43  61  79  97 115 133 151 169 187 205 223 241 259 277 295 313 331 349 367 385 403 421 439 457 475]
 [  8  26  44  62  80  98 116 134 152 170 188 206 224 242 260 278 296 314 332 350 368 386 404 422 440 458 476]
 

In [67]:
print(map_ij)

[[ 0  1  2  3  4  5  6  7  8 18 19 20 21 22 23 24 25 26]
 [ 2  0  1  5  3  4  8  6  7 20 18 19 23 21 22 26 24 25]
 [ 1  2  0  4  5  3  7  8  6 19 20 18 22 23 21 25 26 24]
 [ 6  7  8  0  1  2  3  4  5 24 25 26 18 19 20 21 22 23]
 [ 8  6  7  2  0  1  5  3  4 26 24 25 20 18 19 23 21 22]
 [ 7  8  6  1  2  0  4  5  3 25 26 24 19 20 18 22 23 21]
 [ 3  4  5  6  7  8  0  1  2 21 22 23 24 25 26 18 19 20]
 [ 5  3  4  8  6  7  2  0  1 23 21 22 26 24 25 20 18 19]
 [ 4  5  3  7  8  6  1  2  0 22 23 21 25 26 24 19 20 18]
 [ 9 10 11 12 13 14 15 16 17 27 28 29 30 31 32 33 34 35]
 [11  9 10 14 12 13 17 15 16 29 27 28 32 30 31 35 33 34]
 [10 11  9 13 14 12 16 17 15 28 29 27 31 32 30 34 35 33]
 [15 16 17  9 10 11 12 13 14 33 34 35 27 28 29 30 31 32]
 [17 15 16 11  9 10 14 12 13 35 33 34 29 27 28 32 30 31]
 [16 17 15 10 11  9 13 14 12 34 35 33 28 29 27 31 32 30]
 [12 13 14 15 16 17  9 10 11 30 31 32 33 34 35 27 28 29]
 [14 12 13 17 15 16 11  9 10 32 30 31 35 33 34 29 27 28]
 [13 14 12 16 17 15 10 11  9 31